# Generated by Django 2.0.4 on 2018-07-24 11:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0006_auto_20180424_0708'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favoriterestaurant',
            unique_together={('restaurant', 'user')},
        ),
    ]
